services:
  # dashboard:
  #   image: ssr-dashboard:v1
  #   build:
  #     context: .
  #   ports:
  #     - 8082:3000
  #   networks:
  #     - hireben-network
  #   environment:
  #     APP_SERVER_PORT: 3000
  #     DEMO_SERVICE_ENVIRONMENT: dev
  #     DEMO_SERVICE_FRONTEND_ID: DASHBOARD
  #     DEMO_SERVICE_FRONTEND_SECRET_KEY: hireBenDemoSecretKey
  #     NEXT_PUBLIC_APP_HTTP_CLIENT_TIMEOUT: 7000
  #     NEXT_PUBLIC_APP_PORTAL_BASE_URL: http://localhost:8080
  #     NEXT_PUBLIC_APP_PORTAL_XSRF_COOKIE: "XSRF-TOKEN"
  #     NEXT_PUBLIC_APP_PORTAL_XSRF_HEADER: "X-Csrf-Token"

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - hireben-network

networks:
  hireben-network:
    external: true
