export type View = {
  permissionId: Permission;
  path: string;
  label: string;
};

export enum Permission {
  VIEW_CONSENT = "V-CONSENT",
  VIEW_CONSENT_CREATE = "V-CONSENT-CREATE",
  VIEW_NOTIFICATION = "V-NOTIFICATION",
  VIEW_NOTIFICATION_CREATE = "V-NOTIFICATION-CREATE",
  VIEW_INSURANCE = "V-INSURANCE",
  VIEW_INSURANCE_CREATE = "V-INSURANCE-CREATE",
  VIEW_AUCTION = "V-AUCTION",
  VIEW_AUCTION_CREATE = "V-AUCTION-CREATE",
  CREATE_RESOURCE = "C-RESOURCE",
  READ_RESOURCE = "R-RESOURCE",
  UPDATE_RESOURCE = "U-RESOURCE",
  DELETE_RESOURCE = "D-RESOURCE",
}
